# Generated by Django 3.1.7 on 2021-03-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='location',
            field=models.CharField(default='Not specified', max_length=200),
        ),
    ]
