# Generated by Django 3.1.7 on 2021-03-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_restaurant_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='blogs/static/blogs/images'),
        ),
    ]
