# Generated by Django 3.1.7 on 2021-03-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20210327_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='seated',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='hours',
            field=models.CharField(default='Not provided', max_length=50),
        ),
    ]
