# Generated by Django 3.1.7 on 2021-03-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20210327_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blogs/images/2.jpg', upload_to='posts'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(default='blogs/images/2.jpg', upload_to='logos'),
        ),
    ]
